[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/promptlist/*.db"
  [headers.values]
    Content-Type = "application/octet-stream"
